spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    show-sql: false
    hibernate.jdbc.time_zone: UTC

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/my_blog?currentSchema=my_blog}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:zaq12wsx}

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: skillbox.feduncov@gmail.com
    password: zaq12WSX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

#  default values for initialization:
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 952 456-92-48
  email: dexteraljp1@gmail.com
  copyright: Александр Федунцов
  copyrightFrom: 2005

  captchaDeletionIntervalInHours: 1
  hashForRestorePasswordDeletionIntervalInHours: 1

# Cloudinary configuration
cloudinary:
  cloud_name: https-feduncov-blog-herokuapp-com
  api_key: 311845271332457
  api_secret: GFh0Dmalb2f3HHImHAcmNNbHCAc