spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    show-sql: true

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_blog
    username: postgres
    password: zaq12wsx

#  default values for initialization:
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005