spring:
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: none
    show-sql: true
    hibernate.jdbc.time_zone: UTC

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_blog
    username: postgres
    password: zaq12wsx

#  default values for initialization:
blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 952 456-92-48
  email: dexteraljp1@gmail.com
  copyright: Александр Федунцов
  copyrightFrom: 2005

  captchaDeletionIntervalInHours: 1