insert into tags(name) values('spring');

insert into users(email, is_moderator, name, password, reg_time) values('dexter_aljp1994@gmail.com', 0, 'Ivan', '$2a$12$p8c88WRUSCLVhpUKdWefEu4FzVUFN5tCr/TaP08Y7iMevtfyppFmu', CURRENT_TIMESTAMP);
insert into users(email, is_moderator, name, password, reg_time) values('katrinka@gmail.com', 0, 'Kate', '$2a$12$p8c88WRUSCLVhpUKdWefEu4FzVUFN5tCr/TaP08Y7iMevtfyppFmu', CURRENT_TIMESTAMP);
insert into users(email, is_moderator, name, password, reg_time) values('andrewMail@gmail.com', 0, 'Andrew', '$2a$12$p8c88WRUSCLVhpUKdWefEu4FzVUFN5tCr/TaP08Y7iMevtfyppFmu', CURRENT_TIMESTAMP);

insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'The Spring Boot CLI (Command Line Interface) is a command-line tool that you can use to run and test Spring Boot Applications from a Terminal. The CLI is one of the fastest ways to develop a Spring-based application. How does Spring Boot CLI work? It uses Spring Boot Starter and Spring Boot AutoConfigurate components to', CURRENT_TIMESTAMP, 'Spring Boot CLI', 1, 1);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'Spring Boot Actuator is a sub-project of the Spring Boot Framework. It uses HTTP endpoints to expose operational information about any running application. The main benefit of using this library is that we get health and monitoring metrics from production-ready applications. Moreover, the gathering of metrics, understanding traffic, or knowing the state of the database,', CURRENT_TIMESTAMP, 'Actuator in Spring Boot', 2, 2);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'Internationalization or I18N is a process that makes your application adaptable to different languages and regions without engineering changes on the source code. You can display messages, currencies, date, time etc. according to the specific region or language, likewise you can say internationalization is a readiness of localization. Maven dependency You will only require the', CURRENT_TIMESTAMP, 'Internationalization with Spring Boot', 2, 2);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'A Deque is a linear collection that supports element insertion and removal at both ends. The name deque is short for “double ended queue” and is usually pronounced “deck”. The Deque interface defines methods to access the elements at both ends of the deque. Methods are provided to insert, remove, and examine the element. Each', CURRENT_TIMESTAMP, 'Using Deque in Java', 3, 1);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'In Java, you use the enumeration type to represent a list of predefined constants. But, what if you want to implement a Set interface with the enumeration type, you have got EnumSet in Java to do so. Enum constants are unique and have predefined length, as you can not define a new enum constant at ', CURRENT_TIMESTAMP, 'EnumSet in Java', 0, 3);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'There are read-only wrappers over collections which are known as unmodifiable lists. These lists do not support any modification operations such as add, remove, and clear. Hence, these kinds of lists which guarantee that no change in the Collection object will ever be visible are termed as immutablelist. The Java Collections framework provides the unmodifiableList() […]', CURRENT_TIMESTAMP, 'Using ImmutableList in Java', 0, 3);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'For a One-to-One relationship in JPA, each entity instance is related to a single instance of another entity. It means each row of one entity is referred to one and only one row of another entity. In this post,  you’ll learn how to create a One-to-One relationship between two entities using JPA in a Spring […]', CURRENT_TIMESTAMP, 'One-to-One Relationship in JPA', 5, 1);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'Spring Web applications and services need to process client requests sent over HTTP. When the HTTP clients send data with the request, the data is in the request body. On the application side, you need a mechanism to deserialize data sent in the request body to domain objects. This is done using the @RequestBody annotation. […]', CURRENT_TIMESTAMP, 'The @RequestBody Annotation', 6, 4);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'The Spring Ioc container is at the core of the Spring Framework. BeanFactory and ApplicationContext provide implementations of the IoC container. Both BeanFactory and ApplicationContext are interfaces and there are several implementations that come out of the box with Spring. In this post, I will explain the differences between BeanFactory and ApplicationContext. Major Differences between […]', CURRENT_TIMESTAMP, 'Spring BeanFactory vs ApplicationContext', 12, 1);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'Providing feedback to users is of tremendous importance in a modern Web application. E-mails continue to be the best way to communicate when a user is not active on the platform. Sending e-mail can however take time and may fail. In modern micro-service architecture, the need to give feedback can occur in any of many services. A robust design requires a dedicated service for messaging.', CURRENT_TIMESTAMP, 'Emailing microservice with Apache Kafka', 9, 4);
insert into posts(is_active, moderation_status, text, time, title, view_count, user_id) values(1, 'ACCEPTED', 'A couple of months back, at Sipios, we started a new project to help French companies to face the economic consequences of the Coronavirus crisis. French companies could apply for a loan provided by the French “regions”, as long as the amount asked by all companies was under the limit. Traditionally, it is really painful to apply for a loan and you have to fill lots of paperwork. In this very hard time for companies, we had to create a seamless application that any customer could use and enjoy. That’s why performance was important to not create any additional frustration for our users.', CURRENT_TIMESTAMP, 'How We Reduced a Request Time', 0, 4);

insert into tag2post(tag_id, post_id) values(1,1);
insert into tag2post(tag_id, post_id) values(1,2);
insert into tag2post(tag_id, post_id) values(1,2);
insert into tag2post(tag_id, post_id) values(3,4);
insert into tag2post(tag_id, post_id) values(3,5);
insert into tag2post(tag_id, post_id) values(3,6);
insert into tag2post(tag_id, post_id) values(3,7);
insert into tag2post(tag_id, post_id) values(3,8);

insert into post_votes(time, value, post_id, user_id) values(CURRENT_TIMESTAMP, 1, 1, 1);
insert into post_votes(time, value, post_id, user_id) values(CURRENT_TIMESTAMP, 1, 2, 3);
insert into post_votes(time, value, post_id, user_id) values(CURRENT_TIMESTAMP, 1, 2, 3);
insert into post_votes(time, value, post_id, user_id) values(CURRENT_TIMESTAMP, 1, 2, 3);

